sudo: required
os: linux
dist: Fedora
language: php

php:
  - "7.1"
  
Configured Distribution:
 - Distribution Name: Fedora
 - Release: precise
 - Architecture: amd64
 - Package System: rpm

# command to run tests
script: php cracker_md5_test.php
